### ISSUE TITLE
Create/Improve Chatbot Backend

### ISSUE THREAD

**Issue by ImamuraDev** [HACC2023/Regex#4]
Get Chatbot up and running, improve upon features. 

Tuesday 11/ 7 Goals:
-"Better conversation flow"
-"Full conversation article"

**Comment by ThanhLy1** [comment]
I need someone to test the new implementation and see how it is. Let me know what I should change.

**Comment by ThanhLy1** [comment]
Currently the chatbot is slow to response and this due to large token being sent each time to chatgpt. Will look into this and try to optimized

**Comment by ThanhLy1** [comment]
this issues will be close for now can open it back when chatbot get unresponsive again.
