### ISSUE TITLE
Chatbot UI/UX Styling

### ISSUE THREAD

**Issue by ImamuraDev** [HACC2023/Regex#5]
Work on the front facing part of the chatbot/make it look "nice." You can add more detail about the specifics here if you'd like.

**Comment by ThanhLy1** [comment]
If you take a look at the branch Chatbot, as of 11/5/2023 at 5:02 pm I've updated it a bit. You can change anything you like. let me know if you need more documentation if working on this portion.

Specifically chatbox.jsx
